### ISSUE TITLE
doc build fails with sphinx >=4.0

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#608]
# Description

The `pywps.ext_autodoc` extension does not work with sphinx >=4.0:
```
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v4.0.0

Extension error:
Could not import extension pywps.ext_autodoc (exception: cannot import name 'force_decode')
make: *** [html] Error 2
```

# Environment

- operating system:
- Python version: 
- PyWPS version: 4.4.3
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by huard** [comment]
This should be fixed. 
https://github.com/geopython/pywps/commit/56e9a8928505fa4406a50cfd62b91ca1a83d6dae

**Comment by cehbrecht** [comment]
Fixed by PR #609
